# Generated by Django 3.1.6 on 2021-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('cell', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
