# Generated by Django 3.1.6 on 2021-02-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title1', models.TextField(max_length=20)),
                ('slide_content1', models.TextField(verbose_name=50)),
                ('slide_image1', models.ImageField(upload_to=None)),
                ('slide_title2', models.TextField(max_length=20)),
                ('slide_content2', models.TextField(verbose_name=50)),
                ('slide_image2', models.ImageField(upload_to=None)),
                ('slide_title3', models.TextField(max_length=20)),
                ('slide_content3', models.TextField(verbose_name=50)),
                ('slide_image3', models.ImageField(upload_to=None)),
            ],
        ),
    ]
