# Generated by Django 3.1.6 on 2021-02-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_slide_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.TextField(max_length=50, verbose_name='Mission Title')),
                ('mission_short_text', models.TextField(max_length=100, verbose_name='Mission Short text')),
                ('mission_description', models.TextField(max_length=500, verbose_name='Mission Description')),
                ('vission_title', models.TextField(max_length=50, verbose_name='Vission Title')),
                ('vission_short_text', models.TextField(max_length=100, verbose_name='Vission Short text')),
                ('vission_description', models.TextField(max_length=500, verbose_name='Vission Description')),
                ('journey_title', models.TextField(max_length=50, verbose_name='Journey Title')),
                ('journey_short_text', models.TextField(max_length=100, verbose_name='Journey Short text')),
                ('journey_description', models.TextField(max_length=500, verbose_name='Journey Description')),
            ],
        ),
        migrations.CreateModel(
            name='Board_of_directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Name')),
                ('designation', models.TextField(max_length=20, verbose_name='Designation')),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Brand Title')),
                ('description', models.TextField(max_length=100, verbose_name='Brand Description')),
                ('image', models.ImageField(upload_to=None, verbose_name='Brand Image')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.IntegerField(verbose_name='Total Products')),
                ('active_employees', models.IntegerField(verbose_name='Active Employees')),
                ('active_dealers', models.IntegerField(verbose_name='Active Dealer')),
                ('total_brands', models.IntegerField(verbose_name='Total Brands')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Requester Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Requester Email')),
                ('cell', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsandEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='News Headline')),
                ('description', models.TextField(max_length=500, verbose_name='News Content')),
                ('image', models.ImageField(upload_to=None, verbose_name='News Photo')),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=50, verbose_name='Partner Name')),
                ('partner_logo', models.ImageField(upload_to=None, verbose_name='Partner Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.TextField(verbose_name='Title')),
                ('image', models.ImageField(upload_to=None, verbose_name='Product Image')),
                ('p_description', models.TextField(max_length=500, verbose_name='Product Descreption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_text', models.TextField(max_length=20, verbose_name='Subscription Text')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Topbar_footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_text', models.TextField(max_length=50, verbose_name='Slogan Text')),
                ('facebook_link', models.TextField(verbose_name='Facebook Link')),
                ('twitter_link', models.TextField(verbose_name='Twitter Link')),
                ('googleplus_link', models.TextField(verbose_name='GooglePlus Link')),
                ('linkedin_link', models.TextField(verbose_name='Linkedin Link')),
                ('copyright_text', models.TextField(max_length=50, verbose_name='Copyright')),
            ],
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='cell',
            field=models.CharField(max_length=14, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_content1',
            field=models.TextField(max_length=50, verbose_name='1st Slide Content'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_content2',
            field=models.TextField(max_length=50, verbose_name='2nd Slide Content'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_content3',
            field=models.TextField(max_length=50, verbose_name='3rd Slide Content'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_image1',
            field=models.ImageField(upload_to=None, verbose_name='1st Slide Image'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_image2',
            field=models.ImageField(upload_to=None, verbose_name='2nd Slide Image'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_image3',
            field=models.ImageField(upload_to=None, verbose_name='3rd Slide Image'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_title1',
            field=models.TextField(max_length=20, verbose_name='1st Slide Title'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_title2',
            field=models.TextField(max_length=20, verbose_name='2nd Slide Title'),
        ),
        migrations.AlterField(
            model_name='slide_images',
            name='slide_title3',
            field=models.TextField(max_length=20, verbose_name='3rd Slide Title'),
        ),
    ]
