# Generated by Django 3.1.6 on 2021-02-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_auto_20210217_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.DeleteModel(
            name='Board_of_directors',
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='Company_Overview',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contact_Info',
        ),
        migrations.DeleteModel(
            name='NewsandEvent',
        ),
        migrations.DeleteModel(
            name='Our_partner',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Slide_Images',
        ),
        migrations.DeleteModel(
            name='subscribe',
        ),
        migrations.DeleteModel(
            name='Topbar_footer',
        ),
    ]
