# Generated by Django 3.1.6 on 2021-02-18 12:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_about_us_board_of_directors_brands_company_overview_contact_contact_info_newsandevent_our_partner_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='p_description',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsandevent',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
