# Generated by Django 3.1.7 on 2021-02-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_auto_20210218_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='address',
        ),
        migrations.AddField(
            model_name='contact_info',
            name='address1',
            field=models.TextField(default=1, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_info',
            name='address2',
            field=models.TextField(default=1, verbose_name='Address Line 2'),
            preserve_default=False,
        ),
    ]
