# Generated by Django 3.1.6 on 2021-02-20 11:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_auto_20210220_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(max_length=50, verbose_name='Job Title')),
                ('Description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
