# Generated by Django 3.1.6 on 2021-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Brand Image'),
        ),
    ]
