# Generated by Django 3.1.6 on 2021-02-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20210222_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Brand Image'),
        ),
    ]
