# Generated by Django 3.1.6 on 2021-02-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_auto_20210222_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Product Image'),
        ),
    ]
