# Generated by Django 3.1.6 on 2021-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20210222_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_of_directors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
