# Generated by Django 3.1.7 on 2021-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_auto_20210222_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Products Image'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='career',
            name='Description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newsandevent',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
