# Generated by Django 3.1.6 on 2021-02-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_auto_20210223_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevent',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
