# Generated by Django 3.1.7 on 2021-02-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_auto_20210223_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Products Image'),
        ),
    ]
