# Generated by Django 3.1.7 on 2021-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_newsandevent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevent',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sub_text',
            field=models.TextField(max_length=20, null=True, verbose_name='Subscription Text'),
        ),
    ]
