# Generated by Django 3.1.7 on 2021-03-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_auto_20210301_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='sub_text',
        ),
        migrations.AddField(
            model_name='contact',
            name='sub_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject'),
        ),
    ]
