# Generated by Django 3.1.7 on 2021-03-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_auto_20210301_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sub_text',
        ),
    ]
