# Generated by Django 3.1.7 on 2021-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_remove_contact_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sub_text',
            field=models.TextField(blank=True, max_length=100, verbose_name='Subject'),
        ),
    ]
