# Generated by Django 3.1.7 on 2021-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_remove_topbar_footer_slogan_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar_footer',
            name='f_address',
            field=models.TextField(blank=True, null=True, verbose_name='Footer_address'),
        ),
    ]
