# Generated by Django 3.1.7 on 2021-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_auto_20210303_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevent',
            name='id',
        ),
        migrations.AlterField(
            model_name='newsandevent',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
