# Generated by Django 3.1.7 on 2021-03-03 07:52

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0027_auto_20210303_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsandevent',
            name='slug',
        ),
        migrations.AddField(
            model_name='newsandevent',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
