# Generated by Django 3.1.6 on 2021-03-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_more',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Requester Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Requester Email')),
                ('cell', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('sub_text', models.TextField(blank=True, max_length=100, verbose_name='Subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Requester Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Requester Email')),
                ('cell', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('sub_text', models.TextField(blank=True, max_length=100, verbose_name='Subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Requester Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Requester Email')),
                ('cell', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('sub_text', models.TextField(blank=True, max_length=100, verbose_name='Subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
