# Generated by Django 3.1.7 on 2021-03-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InvestorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_more',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='InvestorPortal.investor'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='InvestorPortal.investor'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='InvestorPortal.investor'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share_rate_history',
            name='date',
            field=models.TextField(max_length=50, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='share_rate_history',
            name='price',
            field=models.IntegerField(),
        ),
    ]
