# Generated by Django 3.1.6 on 2021-03-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_rate_history',
            name='price',
            field=models.IntegerField(),
        ),
    ]
