# Generated by Django 3.1.6 on 2021-03-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorPortal', '0002_auto_20210316_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_rate_history',
            name='date',
            field=models.TextField(max_length=50, verbose_name='Date'),
        ),
    ]
