# Generated by Django 3.1.7 on 2021-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorPortal', '0003_auto_20210320_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_rate_history',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
