# Generated by Django 3.1.7 on 2021-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorPortal', '0003_auto_20210323_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('WITHDRAW', 'WITHDRAW')], max_length=10, verbose_name='Catagory')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('num_of_share', models.IntegerField(verbose_name='Num Of Share/Withdraw Profit')),
                ('total_amount', models.IntegerField(verbose_name='Total Amount')),
            ],
        ),
    ]
